version: "3"
services:
  app:
    container_name: frontend
    build:
      context: .
    volumes:
      - ./src:/app
    command: sh -c "npm run dev"
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
